import { HeadManagerContext } from "next/dist/server/future/route-modules/app-page/vendored/contexts/entrypoints";
import "./globals.css";
import Header from "@/components/Header";
 import {Inter} from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({subsets: ["latin"]});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={inter.className}
      >
      <Header/>
      <main className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
        {children}
      </main>
        <footer className="bg-blue-100 w-full py-12">
          <div className="container mx-auto text-center text-gray-600">
            <p>Made by MD Saqlian Ahmed</p>
          </div>
        </footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
