import "./globals.css";
import Header from "../components/Header";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import EventDropdown from "../components/EventDropdown";
import { Toaster } from "react-hot-toast";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Toaster position="top-right" reverseOrder={false} />
          <Header />
          <main className="min-h-screen bg-[#121212]">{children}</main>
          {/* <div className="pt-">
          <FooterComp />
        </div> */}
          <EventDropdown />
        </body>
      </html>
    </ClerkProvider>
  );
}
